// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcqbiyciwuuyisgdqwin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjcWJpeWNpd3V1eWlzZ2Rxd2luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjQ2NjcsImV4cCI6MjA2MzY0MDY2N30.SW0m_ktow4qYCF8QrzV1laoV8owshIlIFHXUp7RDgck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);